# Docker Compose para Desenvolvimento Local
version: '3.8'

services:
  # Backend FastAPI
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - DB_DRIVER=ODBC Driver 17 for SQL Server
      - DB_SERVER=192.168.1.45\SQLTESTES
      - DB_DATABASE=Cobimob
      - DB_USER=srvcondo1
      - DB_PASSWORD=2025@Condo
      - DB_ENCRYPT=yes
      - DB_TRUST_CERT=yes
      - API_HOST=localhost
      - API_PORT=8080
    restart: unless-stopped
    networks:
      - locacao-network

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_API_BASE_URL=http://localhost:8080/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - locacao-network

networks:
  locacao-network:
    driver: bridge